
# REST client

@host = localhost:3000/api


GET http://{{host}}/child?id=188 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###


###

GET http://{{host}}/user?id=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###

###

PUT http://{{host}}/user/18 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

name=阳光hhh&age=20&male=0
###

###

DELETE http://{{host}}/user/18 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###

###

POST http://{{host}}/user HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###

###
get http://{{host}}/user?page=3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###

###
GET http://localhost:3000/api/user?page=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4
###


###
# add data
POST http://{{host}}/user HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

name=阳光&age=20&male=1

###


###
get http://{{host}}/admin?page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

###


###
post http://{{host}}/admin HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

username=root&password=123456

###


###
put http://{{host}}/admin/1 HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.MTU5MDkwNzA4OTM0Mg.SDNDEOdJz1wtz_WwAYfu5u96n1alXhegZXnRfvlsSd4

username=admin&password=abcd

###

###
post http://{{host}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

username=root&password=123456

###